"use server";
import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation"; import { createClient, getCurrentProfile } from "@/lib/supabase/server"; import { favoritesSchema, heroRatingSchema, heroSchema, profileSchema, ratingSchema, playerSchema } from "@/lib/validators"; import { parsePlayersCsv } from "@/lib/csv"; import { slugify } from "@/lib/utils";
export type ActionState = { error?: string; success?: boolean; issues?: { line: number; error: string }[] };
const generic = "Não foi possível concluir a operação. Verifique os dados e tente novamente.";
type RpcResult = { data: unknown; error: { message: string } | null };
async function callRpc(supabase: { rpc: unknown }, name: string, args: Record<string, unknown>): Promise<RpcResult> { return (supabase.rpc as unknown as (rpcName: string, rpcArgs: Record<string, unknown>) => Promise<RpcResult>)(name, args); }
async function mustBeAdmin() { const profile = await getCurrentProfile(); if (!profile || profile.role !== "admin") throw new Error("Acesso não autorizado"); return profile; }
export async function signOutAction() { const supabase = await createClient(); await supabase.auth.signOut(); redirect("/"); }
export async function submitRatingAction(_: ActionState, formData: FormData): Promise<ActionState> { const parsed = ratingSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? generic }; const supabase=await createClient(); const { data: { user } }=await supabase.auth.getUser(); if (!user) return { error:"Entre para avaliar jogadores." }; const { error } = await callRpc(supabase, "submit_rating", { p_player_slug: parsed.data.playerSlug, p_mode: parsed.data.mode, p_score: parsed.data.score }); if (error) return { error: generic }; revalidatePath("/"); revalidatePath(`/jogadores/${parsed.data.playerSlug}`); return { success:true }; }
export async function submitHeroRatingAction(_: ActionState, formData: FormData): Promise<ActionState> { const parsed=heroRatingSchema.safeParse(Object.fromEntries(formData)); if(!parsed.success)return{error:parsed.error.issues[0]?.message??generic};const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return{error:"Entre para avaliar jogadores."};const{error}=await callRpc(supabase,"submit_hero_rating",{p_player_slug:parsed.data.playerSlug,p_hero_slug:parsed.data.heroSlug,p_score:parsed.data.score});if(error)return{error:generic};revalidatePath(`/jogadores/${parsed.data.playerSlug}`);revalidatePath(`/herois/${parsed.data.heroSlug}`);return{success:true};}
export async function updateProfileAction(input: unknown): Promise<ActionState> { const parsed=profileSchema.safeParse(input); if(!parsed.success) return {error: parsed.error.issues[0]?.message ?? generic}; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) return {error:"Sessão expirada."}; const {error}=await supabase.from("profiles").update({display_name:parsed.data.displayName,gamertag:parsed.data.gamertag,public_slug:parsed.data.publicSlug,avatar_url:parsed.data.avatarUrl||null,bio:parsed.data.bio}).eq("id",user.id); if(error) return {error:generic}; revalidatePath("/perfil"); revalidatePath(`/membros/${parsed.data.publicSlug}`); return {success:true}; }
export async function updateFavoritesAction(heroes: string[]): Promise<ActionState> { const parsed=favoritesSchema.safeParse({heroes}); if(!parsed.success) return {error:parsed.error.issues[0]?.message ??generic}; const supabase=await createClient(); const {error}=await callRpc(supabase,"set_favorite_heroes",{p_hero_slugs:parsed.data.heroes}); if(error)return {error:generic}; revalidatePath("/perfil"); return {success:true}; }
export async function savePlayerAction(input: unknown, existingSlug?: string): Promise<ActionState> { try { await mustBeAdmin(); } catch { return {error:"Acesso não autorizado."}; } const parsed=playerSchema.safeParse(input); if(!parsed.success)return {error:parsed.error.issues[0]?.message??generic}; const supabase=await createClient(); const values={gamertag:parsed.data.gamertag,display_name:parsed.data.displayName||null,bio:parsed.data.bio||"",is_active:parsed.data.isActive}; const result=existingSlug ? await supabase.from("players").update(values).eq("slug",existingSlug) : await supabase.from("players").insert({...values,slug:slugify(parsed.data.gamertag),created_by:(await getCurrentProfile())!.id}); if(result.error)return {error:generic}; revalidatePath("/admin"); revalidatePath("/"); return {success:true}; }
export async function saveHeroAction(slug: string, input: unknown): Promise<ActionState> { try{await mustBeAdmin();}catch{return{error:"Acesso não autorizado."};} const parsed=heroSchema.safeParse(input); if(!parsed.success)return{error:generic}; const supabase=await createClient(); const {error}=await supabase.from("heroes").update({name:parsed.data.name,description:parsed.data.description,is_active:parsed.data.isActive}).eq("slug",slug); if(error)return{error:generic}; revalidatePath("/admin");revalidatePath("/herois");return{success:true}; }
export async function importPlayersAction(csv: string): Promise<ActionState> { try{await mustBeAdmin();}catch{return{error:"Acesso não autorizado."};} const parsed=parsePlayersCsv(csv); if(parsed.issues.length)return {error:"Corrija as linhas indicadas.",issues:parsed.issues}; const supabase=await createClient(); const {data,error}=await callRpc(supabase,"admin_import_players",{p_rows:parsed.rows}); if(error)return{error:generic}; const dbIssues=Array.isArray(data)?data.filter((issue):issue is {line:number;error:string}=>typeof issue==="object"&&issue!==null&&typeof (issue as {error?:unknown}).error==="string").map(issue=>({line:issue.line,error:issue.error})):[]; if(dbIssues.length)return{error:"Algumas linhas não foram importadas.",issues:dbIssues}; revalidatePath("/admin");revalidatePath("/");return{success:true}; }
